Repository Jaredrhd/Archotech, pull requests merged in 2020-05, with the labels that each got.

#17 Jared branch
  .travis.yml
  README.md
  package.json
  tests/math.js
  tests/math.test.js
  tests/something_test.php
Labels: bug, dependencies

#18 Added php test cases
  question.php
  tests/helper.php
  tests/question_test.php
Labels: enhancement

#19 Jared Branch
  .travis.yml
  question.php
  questiontype.php
  tests/helper.php
  tests/question_test.php
  tests/something_test.php
Labels: enhancement

#20 Jonah branch
  tests/logic.js
  tests/logic.test.js
  tests/package.json
Labels: enhancement

#21 Max branch
  tests/logic.js
  tests/logic.test.js
Labels: enhancement

#22 Pre-Release Build
  Drag/SceneGraph.html
Labels: enhancement

#23 Erin branch
  offline_wiki.docx
Labels: documentation

#29 Jared new
  .travis.yml
  Drag/SceneGraph.html
  Drag/SceneGraphLecturer.html
  question.php
  tests/question_test.php
Labels: enhancement

#32 Removed specific feedback and added heading
  edit_logicgate_form.php
  renderer.php
Labels: enhancement
